### PR TITLE
Implement `res.noCache()` to prevent all caching

### PR DESCRIPTION
**Pull request by jwarkentin**

### CODE REVIEW

**Comment by yunong** [comment]
Hi, thanks so much for the PR. Could you please add a unit test for this, and prefix the name with 'gh-762'.

Thanks!

**Comment by jwarkentin** [comment]
I added the test

**Comment by jwarkentin** [comment]
Just following up to see if this can be merged soon. I would love to have it standardized in the library before I launch my code that's using it.

**Comment by yunong** [comment]
Sorry for taking so long -- I'll try to take a look in the next day or two.

**Comment by yunong** [comment]
This has been merged into master. Thanks for contributing

**Pull request closed without merging**
